plugins {
    id "com.android.application"
}

android {
    namespace "be.wacken.planner"
    compileSdk 36

    defaultConfig {
        applicationId "be.wacken.planner"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "0.1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation project(":domain")
    implementation project(":application")
    implementation project(":infrastructure")
}
